spring.application.name=Farmarcia
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/Farmacia
spring.datasource.username=postgres
spring.datasource.password=admin

jwt.secretKey=U2hlIGFza2VkIG1lLCAiU29uLCB3aGVuIEkgZ3JvdyBvbGQKV2lsbCB5b3UgYnV5IG1lIGEgaG91c2Ugb2YgZ29sZD8KQW5kIHdoZW4geW91ciBmYXRoZXIgdHVybnMgdG8gc3RvbmUKV2lsbCB5b3UgdGFrZSBjYXJlIG9mIG1lPyIKU2hlIGFza2VkIG1lLCAiU29uLCB3aGVuIEkgZ3JvdyBvbGQKV2lsbCB5b3UgYnV5IG1lIGEgaG91c2Ugb2YgZ29sZD8KQW5kIHdoZW4geW91ciBmYXRoZXIgdHVybnMgdG8gc3RvbmUKV2lsbCB5b3UgdGFrZSBjYXJlIG9mIG1lPyI=
jwt.expiration=86400000